version: !!str 3

services:
  redis-primary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_primary_data:/bitnami/redis/data

  redis-secondary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - 6380:6379
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_secondary_data:/bitnami/redis/data

volumes:
  redis_primary_data:
    driver: local
  redis_secondary_data:
    driver: local
